import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { createI18n } from 'vue-i18n'
import App from './App.vue'
import router from './router'
import Vant from 'vant'
// 确保 Vant 样式在全局样式之前引入，保证图标字体优先级
import 'vant/lib/index.css'
// 引入全局样式（包含图标字体修复）
import './style.css'

const messages = {
  en: {
   
    common: {
      loading: 'Loading...',
      no_data: 'No Data',
      live_on_chain: '🚀 Live On-Chain:',
      left: 'Left',
      cancel: 'Cancel',
      error: 'Error occurred',
      complete: 'Done',
      copy_failed: 'Copy failed'
    },
    home_btn: {
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      earn: 'Earn',
      service: 'Service',
      team: 'My Team',
      security_center: 'Security Center'
    },
    home: {
      slogan: 'Institutional Transparent Asset Platform',
      platform_transparency: 'Platform Transparency',
      audited_by_certik: 'Audited by CertiK',
      redirecting_certik: 'Redirecting to CertiK Scan...',
      treasury_tvl: 'TREASURY TVL',
      total_payout: 'TOTAL PAYOUT',
      '24h_txns': '24H TXNS',
      since_2025: 'Since 2025',
      on_chain: 'On-Chain',
      market_overview: 'Market Overview',
      all_markets: 'All Markets',
      ticker: {
        prefix: '🚀 Live On-Chain:',
        withdraw: 'User {user} just withdrew {amount} USDT (Tx: {tx})',
        battle: 'User {user} won Price Battle (+{amount} USDT)',
        treasury: 'Treasury added {amount} assets today',
        audit: 'Audit Radar: IDO #{id} verified by CertiK'
      }
    },
    tab: {
      home: 'Home',
      miner: 'Miner',
      trade: 'Trade',
      ido: 'IDO',
      me: 'Me'
    },
    connect: 'Connect Wallet',

    // 充值页面（新增 subtitle）
    deposit: {
      title: 'Deposit Crypto',
      subtitle: 'Deposit USDT via supported networks',  // 新增
      net: 'Select Network',
      addr: 'Deposit Address',
      copy: 'Copy Address',
      tips: 'Send only USDT to this address. Sending any other coins may result in permanent loss.',
      copy_success: 'Address Copied!',
      qr_tip: 'Scan to Deposit', // 新增
      qr_hint: '(Long press to simulate +1000 USDT)'  // 新增
    },

    // 提现页面（新增 subtitle）
    withdraw: {
      title: 'Withdraw USDT',
      subtitle: 'Withdraw USDT to your wallet',
      net: 'Select Network',
      addr: 'Withdraw Address',
      addr_placeholder: 'Enter wallet address',
      amount: 'Amount',
      amount_placeholder: 'Enter amount',
      available_balance: 'Available Balance:',
      max: 'MAX',
      network_fee: 'Network Fee:',
      receive_amount: 'Receive Amount:',
      withdraw_btn: 'Withdraw',
      tip1: 'Ensure the network matches your wallet address',
      tip2: 'Double-check the address before confirming',
      tip3: 'Withdrawal may take 5-30 minutes to process',
      address_pasted: 'Address pasted',
      paste_failed: 'Failed to paste',
      submitted: 'Submitted',
      history_coming_soon: 'History feature coming soon',
      network_trc20: 'TRC20',
      network_erc20: 'ERC20',
      network_bsc: 'BSC',
      estimated_time_prefix: ' Estimated Arrival: about',  // 前缀 + 空格
      min_withdraw: 'Min Withdraw 10 USDT' ,  // 新增：最小提现模板
      coins: {  // 新增 coins 对象
        usdt: 'USDT',  // 英文下显示 'USDT'
        btc: 'BTC',
        eth: 'ETH',
        bnb: 'BNB',
        sol: 'SOL',
        doge: 'DOGE',
        trx: 'TRX',
        beat: 'BEAT',
        zec: 'ZEC',
        aic: 'AIC'
      }
    },

    mining: 'Cloud Mining',
    battle: 'Price Battle',
    round: 'Round',
    left: 'LEFT',
    feed: 'Real-time Feed: Binance & Coinbase Weighted',
    bullish: 'BULLISH',
    bearish: 'BEARISH',
    results: 'Recent Battle Results',
    market: 'Market',
    inst_power: 'Institutional Mining Power',
    update_db: 'Updating Database...',
    safe_sla: 'Safe & SLA Guaranteed',
    daily_rate: 'Daily Rate',
    cycle: 'Cycle',
    min_price: 'Min Price',
    rent_btn: 'Rent Machine Now',

    // 钱包/资产页面
    wallet: {
      est_total_value: 'Est. Total Value',
      wallet_connected: 'Wallet Connected',
      wallet_not_connected: 'Please connect wallet first',
      wallet_address: 'Wallet Address',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      transfer: 'Transfer',
      today_pnl: 'Today\'s PnL',
      account_breakdown: 'Assets Breakdown',
      spot_account: 'Spot Account',
      earn_account: 'Earn Account',
      ieo_locked: 'IEO Locked',
      referral_title: 'Invite Friends & Earn',
      referral_desc: 'When friends trade, you can earn up to',
      referral_rebate: 'rebate',
      referral_earned: 'Earned'
    },
    // 邀请返佣页面
    referral: {
      title: 'Invite & Earn',
      total_earned: 'Total Earned',
      total_referrals: 'Total Referrals',
      people: 'People',
      invite_code: 'Invite Code',
      invite_code_desc: 'Share your invite code to earn commissions',
      copy: 'Copy',
      copy_success: 'Copied!',
      copy_failed: 'Copy failed',
      share_link: 'Link',
      share_qr: 'QR Code',
      share_image: 'Image',
      qr_coming_soon: 'QR code feature coming soon',
      image_coming_soon: 'Share image feature coming soon',
      commission_rules: 'Commission Rules',
      rule_spot: 'Spot Trading',
      rule_spot_desc: 'Friends trade spot',
      rule_futures: 'Futures Trading',
      rule_futures_desc: 'Friends trade futures',
      rule_earn: 'Earn Products',
      rule_earn_desc: 'Friends subscribe earn products',
      recent_earnings: 'Recent Earnings',
      traded: 'traded',
      subscribed: 'subscribed',
      leaderboard: 'Leaderboard',
      referrals: 'referrals',
      go_withdraw: 'Withdraw',
      commission_setting: 'Commission Setting',
      total_commission: 'Total Commission',
      my_share: 'My Share',
      friend_share: 'Friend Share',
      invite_link: 'Invite Link',
      invite_now: 'Invite Friends Now',
      invite_count: 'Invite Count',
      trading_volume: 'Trading Volume',
      yesterday_earnings: 'Yesterday Earnings',
      current_level: 'Current Level',
      need_more: 'Need {count} more to upgrade',
      invite_records: 'Invite Records',
      commission_details: 'Commission Details',
      no_invite_records: 'No invite records yet',
      no_commission_records: 'No commission records yet',
      status_active: 'Active',
      status_inactive: 'Inactive',
      minutes_ago: ' min ago',
      hours_ago: ' hours ago',
      days_ago: ' days ago',
      commission_spot: 'Spot Trading Commission',
      commission_earn: 'Earn Product Commission',
      commission_futures: 'Futures Trading Commission',
      invite_feature_coming_soon: 'Invite feature coming soon',
      announcement_withdraw: 'User {user} just withdrew {amount} USDT',
      announcement_invite: '{user} successfully invited {count} people',
      announcement_earn: '{user} earned {amount} USDT commission',
      scan_to_invite: 'Scan QR code to invite friends',
      scan_to_join: 'Scan QR code to join TruthFi',
      save_poster: 'Save Poster',
      poster_saved: 'Poster saved successfully',
      poster_generate_failed: 'Failed to generate poster',
      qr_generate_failed: 'Failed to generate QR code'
    },
    // 资产页面
    assets: {
      title: 'Assets',
      overview: 'Overview',
      spot: 'Spot',
      leverage: 'Leverage',
      futures: 'Futures',
      earn: 'Earn',
      est_total_value: 'Est. Total Value',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      transfer: 'Transfer',
      convert_small: 'Convert small assets to BNB',
      hide_zero: 'Hide 0 balances',
      search_placeholder: 'Search',
      no_earning_products: 'No active earning products',
      today_pnl: 'Today\'s PnL',
      asset_allocation: 'Asset Allocation',
      spot_account: 'Spot Account',
      earn_account: 'Earn Account',
      ido_pending: 'IEO Pending Unlock',
      ido_pending_desc: 'Pending unlock assets',
      usdt: 'TetherUS',
      btc: 'Bitcoin',
      beat: 'BEAT Token',
      zec: 'Zcash',
      aic: 'AI Comic',
      meme: 'Meme Coin'
    },

    // 理财页面
    earn: {
      title: 'Earn',
      search_placeholder: 'Search',
      tab: {
        hot: 'Hot',
        safe: 'Safe',
        high_yield: 'High Yield',
        simple: 'Simple',
        advanced: 'Advanced'
      },
      total_asset: 'Total Asset Value',
      cumulative_earnings: 'Cumulative Earnings',
      no_products_desc: 'No products available at the moment',
      subscribe: 'Subscribe',
      flexible: 'Flexible',
      days: ' Days',
      reference_annual: 'Reference Annualized',
      tiered_annual_rate: 'Tiered Annual Rate',
      term_days: 'Term (Days)',
      subscribe_amount: 'Subscription Amount',
      enter_amount: 'Enter Amount',
      max: 'MAX',
      available_balance: 'Available Balance',
      quantity_limit: 'Quantity Limit',
      min_investment: 'Minimum Investment',
      available_quota: 'Available Quota',
      individual_quota: 'Individual Total Quota',
      overview: 'Overview',
      real_time_apy: 'Real-time Annualized Yield',
      estimated_daily: 'Estimated Daily Earnings',
      apy_disclaimer: 'Annualized interest rate does not represent actual or estimated earnings calculated in fiat currency.',
      agreement_text: 'I have read and agree to the Wealth Management Service Agreement',
      confirm: 'Confirm',
      subscribe_success: 'Subscription successful',
      no_products: 'No products available',
      help_tooltip: 'Help',
      insufficient_balance: 'Insufficient balance'
    },

    // Earn Center
    miner: {
      total_assets: 'Earn Total Assets',
      total_profit: 'Total Profit',
      stable_earn: 'Stable Earn',
      revenue_record: 'Revenue Record',
      rules_center: 'Rules Center',
      cloud_mining: 'Cloud Mining',
      price_battle: 'Price Battle',
      mining_rules: '云挖矿规则',
      mining_rules_desc: 'After renting a miner, you will earn daily returns at a fixed rate. Returns will be automatically credited after the cycle ends.',
      battle_rules: 'Price Battle Rules',
      battle_rules_desc: 'Predict the price direction, place a bet and wait for the countdown to end. If correct, you get 1.8x payout; if wrong, you lose the bet amount.',
      category_all: 'All',
      category_crypto: 'Crypto',
      category_macro: 'Macro',
      category_sports: 'Sports',
      category_politics: 'Politics',
      volume: 'Vol.',
      ten_thousand: '万'
    },
    // Prediction Market
    prediction: {
      btc_100k: 'Will Bitcoin break $100,000 before the end of January?',
      trump_crypto: 'Will Trump mention "Crypto" in next speech?',
      eth_5k: 'Will Ethereum reach $5,000 in Q1 2026?',
      fed_rates: 'Will the Fed cut rates by 50bps in Q1 2026?',
      lakers_championship: 'Will the Lakers win the 2026 NBA Championship?',
      eth_flip_btc: 'Will ETH flip BTC in market cap by end of 2026?',
      inflation_2pct: 'Will US inflation drop below 2% in 2026?',
      solana_200: 'Will Solana reach $200 before Bitcoin hits $150k?'
    },
    // Launchpad
    launchpad: {
      title: 'TruthFi Launchpad',
      subtitle: 'Access top-tier crypto projects before listing.',
      my_assets: 'My Assets',
      beat_holdings: 'BEAT Holdings',
      usdt_balance: 'USDT Balance',
      progress: 'Progress',
      status_live: 'LIVE',
      status_upcoming: 'UPCOMING',
      status_ended: 'ENDED',
      ido_price: 'IDO Price',
      total_raise: 'Total Raise',
      vesting: 'Vesting'
    },

    // 交易页面
    trade: {
      title: 'Trade',
      buy: 'Buy',
      sell: 'Sell',
      limit_order: 'Limit Order',
      market_order: 'Market Order',
      price: 'Price',
      price_placeholder: 'Enter price',
      amount: 'Amount',
      amount_placeholder: 'Enter amount',
      total: 'Total',
      avail: 'Avail',
      buy_btc: 'Buy BTC',
      sell_btc: 'Sell BTC',
      open_orders: 'Open Orders',
      no_orders: 'No open orders',
      cancel: 'Cancel',
      order_submitted: 'Order submitted',
      order_cancelled: 'Order cancelled',
      fill_all_fields: 'Please fill all fields',
      chart_coming_soon: 'Chart feature coming soon',
      assets: 'Assets',
      cancel_order_confirm: 'Cancel Order',
      cancel_order_message: 'Are you sure you want to cancel this order?',
      cancel_order_confirm_btn: 'Confirm Cancel',
      cancel_order_cancel_btn: 'Keep Order',
      estimated_fee: 'Estimated Fee',
      discount_applied: '(25% discount applied)',
      estimated_value: 'Estimated Value',
      market_price_hint: 'Execute at best market price',
      sellable: 'Sellable',
      frozen: 'Frozen',
      go_trade: 'Go Trade',
      switch_coin: 'Switch Coin',
      select_order_type: 'Select Order Type',
      select_leverage: 'Select Leverage',
      full_position: 'Full Position',
      isolated_position: 'Isolated Position',
      funding_rate: 'Funding Rate',
      open_long: 'Open Long',
      open_short: 'Open Short',
      long: 'Long',
      short: 'Short',
      current_positions: 'Current Positions',
      no_positions: 'No positions',
      positions_tab: 'Positions ({count})',
      open_orders_tab: 'Open Orders',
      trade_history_tab: 'Trade History',
      perpetual: 'Perpetual',
      unrealized_pnl: 'Unrealized P&L',
      liquidation_price: 'Liquidation Price',
      margin_amount: 'Margin',
      position_size: 'Position Size',
      take_profit_stop_loss: 'Take Profit / Stop Loss',
      take_profit_price: 'Take Profit Price',
      stop_loss_price: 'Stop Loss Price',
      close_position: 'Close Position',
      close_position_confirm: 'Close Position',
      close_position_message: 'Are you sure you want to close this position?',
      close_position_confirm_btn: 'Confirm Close',
      close_position_cancel_btn: 'Cancel',
      position_closed: 'Position closed successfully',
      amount_invalid: 'Amount must be greater than 0',
      market_order_submitted: 'Market order submitted',
      limit_order_submitted: 'Limit order submitted',
      switched_to: 'Switched to {symbol}'
    },

    // 市场详情页面
    market: {
      buy: 'Buy',
      sell: 'Sell',
      orderbook: 'Order Book',
      recent_trades: 'Recent Trades',
      time: 'Time',
      price: 'Price',
      amount: 'Amount',
      '24h_high': '24h High',
      '24h_low': '24h Low',
      '24h_vol': '24h Vol',
      '24h_amt': '24h Amt',
      indicators_coming_soon: 'Indicators feature coming soon',
      settings_coming_soon: 'Settings feature coming soon',
      switch_symbol: 'Switch Symbol',
      search_placeholder: 'Search coin',
      name_vol: 'Name / Vol',
      last_price: 'Last Price',
      '24h_chg': '24h Chg%'
    },

    // 历史记录页面
    history: {
      title: 'History',
      empty: 'No records yet',
      transaction: 'Transaction',
      tab: {
        deposit: 'Deposit',
        withdraw: 'Withdraw',
        subscription: 'Subscription'
      },
      status: {
        success: 'Success',
        failed: 'Failed',
        pending: 'Pending'
      }
    },

    // 国库资金明细页面
    treasury: {
      title: 'Treasury Details',
      real_time_assets: 'Real-time Treasury Assets',
      security_level: 'Security Level',
      auditor: 'Audited by',
      net_inflow_30d: 'Last 30 Days Net Inflow',
      on_chain_records: 'Live Accumulation Records (On-Chain)',
      spot_fee: 'Spot Trading Fee',
      futures_fee: 'Futures Trading Fee',
      staking_reward: 'Staking Reward Distribution',
      liquidity_pool_fee: 'Liquidity Pool Fee',
      ido_platform_fee: 'IDO Platform Fee',
      margin_trading_fee: 'Margin Trading Fee',
      txid_copied: 'TxID Copied',
      copy_failed: 'Copy Failed'
    },

    // 链上交易监控页面
    chain_explorer: {
      title: 'On-Chain Transaction Monitor',
      network_status: 'Network Normal',
      current_gas: 'Current Gas',
      block_height: 'Block Height',
      net_flow_24h: '24H Net Flow',
      table_time: 'Time',
      table_type: 'Type',
      table_hash: 'Transaction Hash',
      table_amount: 'Amount',
      table_status: 'Status',
      type_deposit: 'Deposit',
      type_withdraw: 'Withdraw',
      status_success: 'Success',
      status_pending: 'Pending',
      status_confirming: 'Confirming'
    },

    // 安全中心相关
    security: {
      title: 'Security Center',
      security_level: 'Your Account Security Level',
      security_level_medium: 'Medium',
      security_level_high: 'High',
      security_tip: 'Enable more protection to secure your assets',
      phone_verification: 'Phone Verification',
      phone_bound: 'Bound',
      phone_unbound: 'Unbound',
      google_authenticator: 'Google Authenticator (2FA)',
      google_enabled: 'Enabled',
      google_disabled: 'Not Enabled',
      google_auth_status_enabled: 'Google Authenticator is already enabled',
      fund_password: 'Fund Password',
      fund_password_setting: 'Fund Password Setting',
      fund_password_set: 'Set',
      fund_password_unset: 'Not Set',
      // 资金密码设置页面
      fund_password_title: 'Set Fund Password',
      fund_password_step1: 'Enter Password',
      fund_password_step2: 'Confirm Password',
      fund_password_hint: 'Please enter a 6-digit fund password',
      fund_password_confirm_hint: 'Please confirm your fund password',
      fund_password_mismatch: 'Passwords do not match, please re-enter',
      fund_password_success: 'Fund password set successfully',
      fund_password_placeholder: 'Enter 6-digit password',
      // 手机验证页面
      phone_verify_title: 'Phone Verification',
      phone_verify_phone_label: 'Phone Number',
      phone_verify_phone_placeholder: 'Enter phone number',
      phone_verify_code_label: 'Verification Code',
      phone_verify_code_placeholder: 'Enter 6-digit code',
      phone_verify_get_code: 'Get Code',
      phone_verify_countdown: '{seconds}s',
      phone_verify_submit: 'Submit',
      phone_verify_binding_success: 'Binding Successful',
      phone_verify_description: 'Please enter your phone number and verification code to complete binding',
      phone_verify_invalid_phone: 'Please enter a valid phone number',
      phone_verify_code_sent: 'Verification code sent',
      phone_verify_fill_all: 'Please fill in all information',
      phone_verify_code_required: 'Please enter 6-digit verification code',
      phone_verify_invalid_code: 'Invalid verification code format',
      // 谷歌验证页面
      google_auth_title: 'Google Authenticator',
      google_auth_qr_title: 'Scan QR Code',
      google_auth_qr_hint: 'Use Google Authenticator app to scan this QR code',
      google_auth_secret_title: 'Secret Key',
      google_auth_secret_copy: 'Copy',
      google_auth_secret_copied: 'Secret key copied',
      google_auth_refresh_qr: 'Refresh QR Code',
      google_auth_code_label: 'Verification Code',
      google_auth_code_placeholder: 'Enter 6-digit code',
      google_auth_enable_btn: 'Enable Verification',
      google_auth_enable_success: 'Google Authenticator enabled successfully',
      google_auth_description: 'Scan the QR code with Google Authenticator app, then enter the verification code to enable',
      google_auth_qr_refreshed: 'QR code refreshed',
      google_auth_qr_generate_failed: 'Failed to generate QR code',
      google_auth_code_required: 'Please enter 6-digit verification code',
      google_auth_code_invalid: 'Invalid verification code format',
      google_auth_code_hint: 'Verification code updates every 30 seconds, please ensure time synchronization'
    },

    // 设置与资料
    settings: {
      title: 'Settings',
      language: 'Language',
      currency_unit: 'Currency Unit',
      currency_unit_value: 'USD',
      notification: 'Notification',
      privacy_policy: 'Privacy Policy',
      about_us: 'About Us',
      clear_cache: 'Clear Cache',
      cache_size: 'Cache Size',
      cache_cleared: 'Cache cleared',
      // 隐私政策弹窗
      privacy_policy_title: 'Privacy Policy',
      privacy_policy_content: 'TruthFi is committed to protecting your privacy and personal information. We collect and use your data in accordance with applicable laws and regulations. Your data is encrypted and stored securely. We do not share your personal information with third parties without your consent. For more details, please refer to our complete Privacy Policy.',
      privacy_policy_confirm: 'Got it',
      privacy_section1_title: '1. Data Collection',
      privacy_section1_content: 'We only collect user information necessary to provide services, including account information, transaction records, etc. All data is encrypted to ensure your information security.',
      privacy_section2_title: '2. Information Security',
      privacy_section2_content: 'We use industry-leading security technologies to protect your personal information, including but not limited to SSL encrypted transmission, multi-factor authentication and other measures.',
      privacy_section3_title: '3. User Rights',
      privacy_section3_content: 'You have the right to view, modify or delete your personal information at any time. If you need help, please contact our customer service team.',
      privacy_section4_title: '4. Third-Party Services',
      privacy_section4_content: 'We may share some data with third-party service providers to provide a better service experience, but we will not sell your personal information.',
      privacy_section5_title: '5. Policy Updates',
      privacy_section5_content: 'We may update this privacy policy from time to time. Major changes will be notified through in-app notifications or email.',
      // 关于我们弹窗
      about_us_title: 'About TruthFi',
      about_us_version: 'Version v1.0.0',
      about_us_content: 'TruthFi is an institutional asset management platform based on transparency protocol, dedicated to providing users with secure, transparent, and efficient cryptocurrency trading and wealth management services.',
      about_us_content2: 'We use blockchain technology to ensure the transparency of all transaction data, allowing users to track asset flows in real-time and enjoy professional-level financial services.',
      about_us_confirm: 'Got it',
      security_center: 'Security Center',
      // 退出登录确认弹窗
      logout_confirm_title: 'Confirm Logout',
      logout_confirm_message: 'Are you sure you want to logout? You will need to reconnect your wallet after logging out.',
      logout_confirm_btn: 'Confirm',
      logout_cancel_btn: 'Cancel',
      logout_success: 'Logged out successfully',
      // 通知设置
      notification_enabled: 'Push notifications enabled',
      notification_disabled: 'Notifications disabled',
      notif_market_up: '{symbol}/USDT Market Up',
      notif_market_down: '{symbol}/USDT Market Down',
      notif_market_current: 'Current Price: ${price} ({change}%)'
    },

    // 个人资料
    profile: {
      title: 'Profile',
      nickname: 'Nickname',
      nickname_placeholder: 'Enter nickname',
      nickname_rule: 'Nickname must be 2-12 characters, only letters, numbers, and Chinese characters allowed',
      nickname_success: 'Nickname updated successfully',
      avatar: 'Avatar',
      avatar_take_photo: 'Take Photo',
      avatar_choose_album: 'Choose from Album',
      avatar_upload_demo: 'Demo environment does not support actual upload',
      uid: 'UID',
      register_time: 'Registration Time',
      bnb_fee_discount: 'Use BNB to Pay Trading Fees',
      bnb_fee_discount_desc: 'Enjoy 25% discount',
      bnb_interest_discount: 'Use BNB to Pay Leverage Interest',
      bnb_interest_discount_desc: 'Enjoy 5% discount',
      spot_fee_rate: 'Spot Fee Rate',
      spot_fee_maker: 'Maker',
      spot_fee_taker: 'Taker',
      futures_fee_rate: 'Futures Fee Rate',
      futures_fee_maker: 'Maker',
      futures_fee_taker: 'Taker',
      google_auth: 'Google Authenticator',
      logout: 'Logout',
      id_copied: 'ID copied',
      bnb_fee_enabled: 'BNB fee discount enabled',
      bnb_fee_disabled: 'BNB fee discount disabled',
      bnb_interest_enabled: 'BNB interest discount enabled',
      bnb_interest_disabled: 'BNB interest discount disabled',
      google_auth_disabled: 'Google Authenticator disabled'
    },

    // 客服支持
    support: {
      title: 'Help & Support',
      official_service: 'TruthFi Official Customer Service',
      service_subtitle: 'Professional customer service team available 24/7',
      service_promise: 'Service Promise',
      privacy_encryption: 'Privacy Encryption',
      fast_response: 'Fast Response',
      human_service: 'Human Service',
      contact_service: 'Contact Online Service',
      connecting: 'Connecting to secure line...',
      service_busy: 'Currently there are many inquiries, please try again later or contact Telegram community',
      telegram_community: 'Join Official Telegram Community',
      telegram_redirect: 'Redirecting to Telegram community...'
    }
  },
  zh: {
    
    common: {
      loading: '加载中...',
      no_data: '暂无数据',
      live_on_chain: '🚀 链上实况:',
      left: '剩余',
      cancel: '取消',
      error: '操作失败',
      complete: '完成',
      copy_failed: '复制失败'
    },
    home_btn: {
      deposit: '充值',
      withdraw: '提现',
      earn: '理财',
      service: '客服',
      team: '团队',
      security_center: '安全中心'
    },
    home: {
      slogan: '机构级透明资产平台',
      platform_transparency: '平台透明度',
      audited_by_certik: 'Audited by CertiK',
      redirecting_certik: '正在跳转到 CertiK 扫描...',
      treasury_tvl: '国库资产',
      total_payout: '累计支出',
      '24h_txns': '24h 链上交易',
      since_2025: '自 2025 年起',
      on_chain: '链上数据',
      market_overview: '市场概览',
      all_markets: '所有市场',
      ticker: {
        prefix: '🚀 链上实况:',
        withdraw: '用户 {user} 刚刚提取 {amount} USDT (Tx: {tx})',
        battle: '用户 {user} 赢得了价格对决 (+{amount} USDT)',
        treasury: '国库今日新增资产 {amount}',
        audit: '审计雷达: IDO #{id} 已通过 CertiK 验证'
      }
    },
    tab: {
      home: '首页',
      miner: '赚币',
      trade: '交易',
      ido: '认购',
      me: '我的'
    },
    connect: '连接钱包',

    // 充值页面（新增 subtitle）
    deposit: {
      title: '加密货币充值',
      subtitle: '通过支持的网络充值 USDT',  // 新增
      net: '选择网络',
      addr: '充值地址',
      copy: '复制地址',
      tips: '请仅向该地址转入 USDT，转入其他币种可能无法找回。',
      copy_success: '地址已复制！',
      qr_tip: '扫码充值',  // 新增
      qr_hint: '(长按模拟 +1000 USDT)'  // 新增

    },

    // 提现页面（新增 subtitle）
    withdraw: {
      title: '提现 USDT',
      subtitle: '将 USDT 提现到您的钱包',
      net: '选择网络',
      addr: '提现地址',
      addr_placeholder: '请输入钱包地址',
      amount: '金额',
      amount_placeholder: '请输入金额',
      available_balance: '可用余额：',
      max: '最大',
      network_fee: '网络费用：',
      receive_amount: '接收金额：',
      withdraw_btn: '提现',
      tip1: '请确保网络与您的钱包地址匹配',
      tip2: '确认前请仔细核对地址',
      tip3: '提现可能需要 5-30 分钟处理',
      address_pasted: '地址已粘贴',
      paste_failed: '粘贴失败',
      submitted: '已提交',
      history_coming_soon: '历史记录功能即将推出',
      network_trc20: 'TRC20',
      network_erc20: 'ERC20',
      network_bsc: 'BSC',
      estimated_time_prefix: ' 预计到账: 约', // 新增
      min_withdraw: '最小提现10 USDT' , // 新增
      coins: {// 新增 coins 对象
        usdt: '泰达币',  // 中文下显示 '泰达币'
        btc: '比特币',
        eth: '以太坊',
        bnb: '币安币',
        sol: 'Solana',
        doge: '狗狗币',
        trx: '波场币',
        beat: 'BEAT 代币',
        aic: 'AIC 代币',
        zec: 'Zcash',
      }
    },

    mining: '云挖矿',
    battle: '价格对决',
    round: '轮次',
    left: '剩余',
    feed: '实时数据: 币安 & Coinbase 加权',
    bullish: '看涨 (买多)',
    bearish: '看跌 (买空)',
    results: '近期对决结果',
    market: '市场',
    inst_power: '机构级算力池',
    update_db: '正在同步链上数据...',
    safe_sla: 'SLA 协议保障',
    daily_rate: '日收益率',
    cycle: '周期',
    min_price: '起购价',
    rent_btn: '立即租赁矿机',

    // 钱包/资产页面
    wallet: {
      est_total_value: '预估总资产',
      wallet_connected: '钱包已连接',
      wallet_not_connected: '请先连接钱包',
      wallet_address: '钱包地址',
      deposit: '充值',
      withdraw: '提现',
      transfer: '转账',
      today_pnl: '今日盈亏',
      account_breakdown: '账户资产分布',
      spot_account: '现货账户',
      earn_account: '赚币账户',
      ieo_locked: 'IEO 待解锁',
      referral_title: '邀请好友赚佣金',
      referral_desc: '好友交易，您最高可获',
      referral_rebate: '返佣',
      referral_earned: '已赚'
    },
    // 邀请返佣页面
    referral: {
      title: '邀请返佣',
      total_earned: '累计收益',
      total_referrals: '邀请人数',
      people: '人',
      invite_code: '邀请码',
      invite_code_desc: '分享您的邀请码，赚取佣金',
      copy: '复制',
      copy_success: '邀请码已复制！',
      copy_failed: '复制失败',
      share_link: '链接',
      share_qr: '二维码',
      share_image: '图片',
      qr_coming_soon: '二维码功能即将推出',
      image_coming_soon: '分享图片功能即将推出',
      commission_rules: '返佣规则',
      rule_spot: '现货交易',
      rule_spot_desc: '好友进行现货交易',
      rule_futures: '合约交易',
      rule_futures_desc: '好友进行合约交易',
      rule_earn: '理财产品',
      rule_earn_desc: '好友申购理财产品',
      recent_earnings: '最近收益',
      traded: '交易',
      subscribed: '申购',
      leaderboard: '排行榜',
      referrals: '邀请',
      go_withdraw: '去提现',
      commission_setting: '返佣设置',
      total_commission: '总返佣',
      my_share: '我的',
      friend_share: '好友',
      invite_link: '邀请链接',
      invite_now: '立即邀请好友',
      invite_count: '邀请人数',
      trading_volume: '交易额',
      yesterday_earnings: '昨日收益',
      current_level: '当前等级',
      need_more: '差 {count} 人升级',
      invite_records: '邀请记录',
      commission_details: '返佣明细',
      no_invite_records: '暂无邀请记录',
      no_commission_records: '暂无返佣明细',
      status_active: '已激活',
      status_inactive: '未激活',
      minutes_ago: '分钟前',
      hours_ago: '小时前',
      days_ago: '天前',
      commission_spot: '现货交易返佣',
      commission_earn: '理财产品返佣',
      commission_futures: '合约交易返佣',
      invite_feature_coming_soon: '邀请功能即将推出',
      announcement_withdraw: '用户 {user} 刚刚提现 {amount} USDT',
      announcement_invite: '{user} 成功邀请 {count} 人',
      announcement_earn: '{user} 获得 {amount} USDT 返佣',
      scan_to_invite: '扫描二维码邀请好友',
      scan_to_join: '扫描二维码加入 TruthFi',
      save_poster: '保存海报',
      poster_saved: '海报已保存',
      poster_generate_failed: '海报生成失败',
      qr_generate_failed: '二维码生成失败'
    },
    // 资产页面
    assets: {
      title: '资产',
      overview: '概览',
      spot: '现货',
      leverage: '杠杆',
      futures: '合约',
      earn: '理财',
      est_total_value: '预估总资产',
      deposit: '充值',
      withdraw: '提现',
      transfer: '转账',
      convert_small: '将小额资产转换为 BNB',
      hide_zero: '隐藏零余额',
      search_placeholder: '搜索',
      no_earning_products: '暂无理财产品',
      today_pnl: '今日盈亏',
      asset_allocation: '账户资产分布',
      spot_account: '现货账户',
      earn_account: '赚币账户',
      ido_pending: 'IEO 待解锁',
      ido_pending_desc: '待解锁资产',
      usdt: '泰达币',
      btc: '比特币',
      beat: 'BEAT 代币',
      zec: 'Zcash',
      aic: 'AI 漫画',
      meme: '模因币'
    },

    // 理财页面
    earn: {
      title: '理财',
      search_placeholder: '搜索',
      tab: {
        hot: '热门',
        safe: '保本',
        high_yield: '高收益',
        simple: '稳健',
        advanced: '进阶'
      },
      subscribe: '申购',
      flexible: '活期',
      days: '天',
      reference_annual: '参考年化',
      tiered_annual_rate: '阶梯年利率',
      term_days: '期限(天)',
      subscribe_amount: '申购金额',
      enter_amount: '输入金额',
      max: '全部',
      available_balance: '可用余额',
      quantity_limit: '数量限制',
      min_investment: '最少可投',
      available_quota: '可用额度',
      individual_quota: '个人总额度',
      overview: '概览',
      real_time_apy: '实时年化收益率',
      estimated_daily: '估计每日收益',
      apy_disclaimer: '年利率并不表示以法币计算的实际或预计收益。',
      agreement_text: '我已阅读并同意 币安理财服务协议',
      confirm: '确认',
      subscribe_success: '申购成功',
      no_products: '暂无产品',
      no_products_desc: '暂无可用产品，请稍后再试',
      help_tooltip: '帮助',
      insufficient_balance: '余额不足',
      total_asset: '理财总资产',
      cumulative_earnings: '累计收益'
    },

    // 聚合赚币中心
    miner: {
      total_assets: '赚币账户总资产',
      total_profit: '累计收益',
      stable_earn: '稳健理财',
      revenue_record: '收益记录',
      rules_center: '规则中心',
      cloud_mining: '云挖矿',
      price_battle: '价格对决',
      mining_rules: '云挖矿规则',
      mining_rules_desc: '租用矿机后，每日按固定收益率获得收益。收益将在周期结束后自动到账。',
      battle_rules: '价格对决规则',
      battle_rules_desc: '预测价格涨跌方向，下注后等待倒计时结束。若预测正确，将获得1.8倍赔付；若预测错误，将损失下注金额。',
      category_all: '全部',
      category_crypto: '加密',
      category_macro: '宏观',
      category_sports: '体育',
      category_politics: '政治',
      volume: '成交量',
      ten_thousand: '万'
    },
    // Prediction Market
    prediction: {
      btc_100k: 'Bitcoin 会在 1 月底前突破 $100,000 吗？',
      trump_crypto: '特朗普会在下次演讲中提及"加密货币"吗？',
      eth_5k: 'Ethereum 会在 2026 年 Q1 达到 $5,000 吗？',
      fed_rates: '美联储会在 2026 年 Q1 降息 50 个基点吗？',
      lakers_championship: '湖人队会赢得 2026 年 NBA 总冠军吗？',
      eth_flip_btc: 'ETH 会在 2026 年底前市值超越 BTC 吗？',
      inflation_2pct: '美国通胀率会在 2026 年降至 2% 以下吗？',
      solana_200: 'Solana 会在 Bitcoin 达到 $150k 之前达到 $200 吗？'
    },
    // Launchpad
    launchpad: {
      title: 'TruthFi 认购',
      subtitle: '在上市前抢先体验顶级加密项目。',
      my_assets: '我的资产',
      beat_holdings: 'BEAT 持仓',
      usdt_balance: 'USDT 余额',
      progress: '认购进度',
      status_live: '进行中',
      status_upcoming: '即将开始',
      status_ended: '已结束',
      ido_price: '认购价格',
      total_raise: '募资总额',
      vesting: '解锁规则'
    },

    // 交易页面
    
    trade: {
      title: '交易',
      buy: '买入',
      sell: '卖出',
      limit_order: '限价单',
      market_order: '市价单',
      price: '价格',
      price_placeholder: '请输入价格',
      amount: '数量',
      amount_placeholder: '请输入数量',
      total: '总额',
      avail: '可用',
      buy_btc: '买入 BTC',
      sell_btc: '卖出 BTC',
      open_orders: '当前委托',
      no_orders: '暂无委托订单',
      cancel: '撤单',
      order_submitted: '订单已提交',
      order_cancelled: '订单已取消',
      fill_all_fields: '请填写所有字段',
      chart_coming_soon: '图表功能即将推出',
      assets: '资产',
      cancel_order_confirm: '确认撤单',
      cancel_order_message: '确定要撤销此订单吗？',
      cancel_order_confirm_btn: '确认撤单',
      cancel_order_cancel_btn: '保留订单',
      estimated_fee: '预估手续费',
      discount_applied: '（已享25%折扣）',
      estimated_value: '估值',
      market_price_hint: '以当前最优价格成交',
      sellable: '可卖',
      frozen: '冻结',
      go_trade: '去交易',
      switch_coin: '切换币种',
      select_order_type: '选择订单类型',
      select_leverage: '选择杠杆倍数',
      full_position: '全仓',
      isolated_position: '逐仓',
      funding_rate: '资金费率',
      open_long: '开多',
      open_short: '开空',
      long: '做多',
      short: '做空',
      current_positions: '当前持仓',
      no_positions: '暂无持仓',
      positions_tab: '持有仓位 ({count})',
      open_orders_tab: '当前委托',
      trade_history_tab: '历史成交',
      perpetual: '永续',
      unrealized_pnl: '未实现盈亏',
      liquidation_price: '强平价格',
      margin_amount: '保证金',
      position_size: '仓位数量',
      take_profit_stop_loss: '止盈止损',
      take_profit_price: '止盈价格',
      stop_loss_price: '止损价格',
      close_position: '平仓',
      close_position_confirm: '确认平仓',
      close_position_message: '确定要平仓此持仓吗？',
      close_position_confirm_btn: '确认平仓',
      close_position_cancel_btn: '取消',
      position_closed: '平仓成功',
      amount_invalid: '数量必须大于 0',
      market_order_submitted: '市价单提交成功',
      limit_order_submitted: '限价单提交成功',
      switched_to: '已切换到 {symbol}'
    },

    // 市场详情页面
    market: {
      buy: '买入',
      sell: '卖出',
      orderbook: '盘口',
      recent_trades: '最新成交',
      time: '时间',
      price: '价格',
      amount: '数量',
      '24h_high': '24h最高',
      '24h_low': '24h最低',
      '24h_vol': '24h成交量',
      '24h_amt': '24h成交额',
      indicators_coming_soon: '指标功能即将推出',
      settings_coming_soon: '设置功能即将推出',
      switch_symbol: '切换币种',
      search_placeholder: '搜索币种',
      name_vol: '名称 / 成交额',
      last_price: '最新价',
      '24h_chg': '24h涨跌'
    },

    // 历史记录页面
    history: {
      title: '历史记录',
      empty: '暂无记录',
      transaction: '交易',
      tab: {
        deposit: '充值',
        withdraw: '提现',
        subscription: '认购'
      },
      status: {
        success: '成功',
        failed: '失败',
        pending: '进行中'
      }
    },

    // 国库资金明细页面
    treasury: {
      title: '国库资金明细',
      real_time_assets: '实时国库资产',
      security_level: '安全评级',
      auditor: '审计方',
      net_inflow_30d: '近 30 日资金净流入',
      on_chain_records: '实时归集记录 (On-Chain)',
      spot_fee: '现货交易手续费',
      futures_fee: '合约交易手续费',
      staking_reward: '质押奖励分配',
      liquidity_pool_fee: '流动性池手续费',
      ido_platform_fee: 'IDO 平台手续费',
      margin_trading_fee: '杠杆交易手续费',
      txid_copied: 'TxID 已复制',
      copy_failed: '复制失败'
    },

    // 链上交易监控页面
    chain_explorer: {
      title: '链上交易监控',
      network_status: '网络正常',
      current_gas: '当前 Gas',
      block_height: '区块高度',
      net_flow_24h: '24H 净流入',
      table_time: '时间',
      table_type: '类型',
      table_hash: '交易哈希',
      table_amount: '金额',
      table_status: '状态',
      type_deposit: '充值',
      type_withdraw: '提现',
      status_success: '成功',
      status_pending: '确认中',
      status_confirming: '确认中'
    },

    // 安全中心相关
    security: {
      title: '安全中心',
      security_level: '您的账户安全等级',
      security_level_medium: '中',
      security_level_high: '高',
      security_tip: '开启更多保护，保障资产安全',
      phone_verification: '手机验证',
      phone_bound: '已绑定',
      phone_unbound: '去绑定',
      google_authenticator: '谷歌验证器 (2FA)',
      google_enabled: '已开启',
      google_disabled: '未开启',
      google_auth_status_enabled: '谷歌验证器已开启',
      fund_password: '资金密码',
      fund_password_setting: '资金密码设置',
      fund_password_set: '已设置',
      fund_password_unset: '未设置',
      // 资金密码设置页面
      fund_password_title: '设置资金密码',
      fund_password_step1: '输入密码',
      fund_password_step2: '确认密码',
      fund_password_hint: '请输入6位数字资金密码',
      fund_password_confirm_hint: '请再次输入密码确认',
      fund_password_mismatch: '两次输入的密码不一致，请重新输入',
      fund_password_success: '资金密码设置成功',
      fund_password_placeholder: '请输入6位数字',
      // 手机验证页面
      phone_verify_title: '手机验证',
      phone_verify_phone_label: '手机号码',
      phone_verify_phone_placeholder: '请输入手机号码',
      phone_verify_code_label: '验证码',
      phone_verify_code_placeholder: '请输入6位验证码',
      phone_verify_get_code: '获取验证码',
      phone_verify_countdown: '{seconds}秒',
      phone_verify_submit: '提交',
      phone_verify_binding_success: '绑定成功',
      phone_verify_description: '绑定手机号后，可用于登录验证和找回密码',
      phone_verify_invalid_phone: '请输入正确的手机号',
      phone_verify_code_sent: '验证码已发送',
      phone_verify_fill_all: '请填写完整信息',
      phone_verify_code_required: '请输入6位验证码',
      phone_verify_invalid_code: '验证码格式不正确',
      // 谷歌验证页面
      google_auth_title: '谷歌验证器',
      google_auth_qr_title: '扫描二维码',
      google_auth_qr_hint: '使用谷歌验证器 App 扫描此二维码',
      google_auth_secret_title: '密钥',
      google_auth_secret_copy: '复制',
      google_auth_secret_copied: '密钥已复制',
      google_auth_refresh_qr: '刷新二维码',
      google_auth_code_label: '验证码',
      google_auth_code_placeholder: '请输入6位验证码',
      google_auth_enable_btn: '开启验证',
      google_auth_enable_success: '谷歌验证器开启成功',
      google_auth_description: '使用谷歌验证器 App 扫描二维码，然后输入验证码以开启',
      google_auth_qr_refreshed: '二维码已刷新',
      google_auth_qr_generate_failed: '二维码生成失败',
      google_auth_code_required: '请输入6位验证码',
      google_auth_code_invalid: '验证码格式不正确',
      google_auth_code_hint: '验证码每30秒更新一次，请确保时间同步'
    },

    // 设置与资料
    settings: {
      title: '通用设置',
      language: '语言',
      currency_unit: '汇率单位',
      currency_unit_value: 'USD',
      notification: '通知设置',
      privacy_policy: '隐私政策',
      about_us: '关于我们',
      clear_cache: '清除缓存',
      cache_size: '缓存大小',
      cache_cleared: '缓存已清除',
      // 隐私政策弹窗
      privacy_policy_title: '隐私政策',
      privacy_policy_content: 'TruthFi 致力于保护您的隐私和个人信息。我们根据适用的法律法规收集和使用您的数据。您的数据经过加密并安全存储。未经您同意，我们不会与第三方分享您的个人信息。更多详情，请参阅我们的完整隐私政策。',
      privacy_policy_confirm: '我知道了',
      privacy_section1_title: '1. 数据收集',
      privacy_section1_content: '我们仅收集提供服务所必需的用户信息，包括账户信息、交易记录等。所有数据均经过加密处理，确保您的信息安全。',
      privacy_section2_title: '2. 信息安全',
      privacy_section2_content: '我们采用行业领先的安全技术保护您的个人信息，包括但不限于SSL加密传输、多重身份验证等措施。',
      privacy_section3_title: '3. 用户权利',
      privacy_section3_content: '您有权随时查看、修改或删除您的个人信息。如需帮助，请联系我们的客服团队。',
      privacy_section4_title: '4. 第三方服务',
      privacy_section4_content: '我们可能与第三方服务提供商共享部分数据以提供更好的服务体验，但不会出售您的个人信息。',
      privacy_section5_title: '5. 政策更新',
      privacy_section5_content: '我们可能会不定期更新本隐私政策。重大变更将通过站内通知或邮件方式告知您。',
      // 关于我们弹窗
      about_us_title: '关于 TruthFi',
      about_us_version: '版本 v1.0.0',
      about_us_content: 'TruthFi 是机构级透明资产平台，致力于为用户提供安全、透明、高效的加密资产交易与理财服务。',
      about_us_content2: '我们通过区块链技术确保所有交易数据的公开透明，让用户能够实时追踪资产流向，享受专业级的金融服务体验。',
      about_us_confirm: '我知道了',
      security_center: '安全中心',
      // 退出登录确认弹窗
      logout_confirm_title: '确认退出',
      logout_confirm_message: '确定要退出登录吗？退出后需要重新连接钱包。',
      logout_confirm_btn: '确认',
      logout_cancel_btn: '取消',
      logout_success: '退出成功',
      // 通知设置
      notification_enabled: '推送通知已开启',
      notification_disabled: '通知已停用',
      notif_market_up: '{symbol}/USDT 行情上涨',
      notif_market_down: '{symbol}/USDT 行情下跌',
      notif_market_current: '当前价格: ${price} ({change}%)'
    },

    // 个人资料
    profile: {
      title: '个人资料',
      nickname: '昵称',
      nickname_placeholder: '请输入昵称',
      nickname_rule: '昵称长度必须在 2-12 位之间，仅允许输入中英文和数字',
      nickname_success: '昵称修改成功',
      avatar: '头像',
      avatar_take_photo: '拍照',
      avatar_choose_album: '相册',
      avatar_upload_demo: '演示环境暂不支持实际上传',
      uid: 'UID',
      register_time: '注册时间',
      bnb_fee_discount: '使用BNB支付交易手续费',
      bnb_fee_discount_desc: '享受 25%折扣',
      bnb_interest_discount: '使用BNB支付杠杆利息',
      bnb_interest_discount_desc: '享受 5%折扣',
      spot_fee_rate: '现货费率',
      spot_fee_maker: '挂单',
      spot_fee_taker: '吃单',
      futures_fee_rate: 'U本位费率',
      futures_fee_maker: '挂单',
      futures_fee_taker: '吃单',
      google_auth: '谷歌验证',
      logout: '退出登录',
      id_copied: 'ID 已复制',
      bnb_fee_enabled: '已开启BNB手续费折抵',
      bnb_fee_disabled: '已关闭BNB手续费折抵',
      bnb_interest_enabled: '已开启BNB利息折抵',
      bnb_interest_disabled: '已关闭BNB利息折抵',
      google_auth_disabled: '已关闭谷歌验证'
    },

    // 客服支持
    support: {
      title: '帮助与支持',
      official_service: 'TruthFi 官方客服',
      service_subtitle: '专业客服团队 7×24h 在线',
      service_promise: '服务承诺',
      privacy_encryption: '隐私加密',
      fast_response: '极速响应',
      human_service: '真人服务',
      contact_service: '联系在线客服',
      connecting: '正在为您接入安全线路...',
      service_busy: '当前咨询人数较多，请稍后再试或联系 Telegram 社区',
      telegram_community: '加入官方 Telegram 社区',
      telegram_redirect: '正在跳转到 Telegram 社区...'
    }
  }
}

// 在 createI18n 之前添加这行代码，从 localStorage 获取保存的语言，如果没有则默认 'en'（或 'zh'，根据您的偏好）
const savedLanguage = localStorage.getItem('language') || 'en';  // 默认英文，您可以改为 'zh' 如果想默认中文

const i18n = createI18n({
  legacy: false,
  locale: savedLanguage,  // 修改为动态从 localStorage 获取
  globalInjection: true,
  messages
})

const app = createApp(App)
const pinia = createPinia()
app.use(pinia)
app.use(i18n)
app.use(router)
app.use(Vant)
app.mount('#app')

